### ISSUE TITLE
[Discussion] 배너관련 토론

### ISSUE THREAD

**Issue by jjoung-2j** [jjoung-2j/Mediinfora#18]
### 배너를 통일화 하는게 좋을것같아서 토론글 올립니다. 각자 의견 남겨주세요.(우선 1번 안건부터 부탁드립니다)
- 현재 페이지 존재 - 진료예약, 공지사항

---

### [안건1] 배너 통일화방식
배너 방식과 모양 등 에 대해 서술

### [안건2] 배너 안 글씨 위치
-> 좌측, 가운데

---
[참고 이미지]
![KakaoTalk_20240629_201137551](https://github.com/jjoung-2j/Medinfora/assets/145014345/c08fcf48-895c-44e3-bbab-fc59c5ee96a5)
![공지사항 배너](https://github.com/jjoung-2j/Medinfora/assets/145014345/c32706c6-b3a9-4665-8b09-322bb55eef93)

**Comment by kshksh723** [comment]
[승혜 의견] 저도 공지사항이나 qna 게시판은 통일하면 좋을 것 같아요!

**Comment by jjoung-2j** [comment]
게시글에서 따로 comment 로 제 의견에 대한 글옮겨요.

**Comment by jjoung-2j** [comment]
- [혜정] 의견
공지사항이나 Q&A 게시판 등 게시판이 있는 배너들은 통일화 하고 나머지는 각자 화면 규격에 따라 하는게 괜찮을 것 같다고 생각합니다.

**Comment by nime0110** [comment]
[성심] 의견
안건 1 - 게시판 형식의 배너는 통일(공지사항, 회원목록 등 게시판의 형태가 있는 것) 하는 게 좋다고 생각합니다.
안건 2 - 가운데 배치가 좋습니다.

**Comment by jjoung-2j** [comment]
[혜정] 두번째 안건 의견
배너글씨는 가운데 배치가 좋은것같아요

**Comment by Forest-Seo** [comment]
- [동혁] 의견
    이미지가 있는 배너를 한다면 css양식을 해더에 등록하여 통일성있게 하는것이 좋을꺼같고, 괜찮을꺼 같다 생각하는 조건은  배너이미지의 종류가 다양했으면 좋겠어요 (비슷한 패턴), 배너 글씨도 사이드바가 없다면 가운데 배치가 좋을꺼같아요!

**Comment by exhuni777** [comment]
[지훈] 의견
• 현재 적용하고자 하는 배너가 기능이 아닌 단순 페이지 소개 내용만 전달하는 것으로 사료되어 게시판 느낌에 페이지인 경우 header 아래부분에 참고이미지와 같은 디자인이 좋을것 같습니다. 다만, 배경색상에 경우 페이지 별로 조금씩 다르게하고 패턴이나 문양이 있다면 패턴이나 문양은 동일하게 적용하는게 통일감을 줄거 같습니다.

• 배너 안 글자의 위치는 아래 두가지 중 선택하는게 나을거 같습니다.
- 가운데, 페이지이름 아래 소개(작은글씨)
- 좌측, 페이지이름 옆 소개(작은글씨)

반응형에 경우 가운데, 페이지이름 만 보이도록 바뀌게 설정
