### ISSUE TITLE
[Discussion] 공지사항 뷰단에 대해 토의

### ISSUE THREAD

**Issue by jjoung-2j** [jjoung-2j/Mediinfora#19]
### 현재 공지사항 뷰단에 대한 의견 남겨주세요

---

- ### 웹 VIEW
![공지사항1](https://github.com/jjoung-2j/Medinfora/assets/145014345/ac331cfb-7e95-4260-8424-4b775d159340)

---

- ### 반응형 VIEW
![공지사항2](https://github.com/jjoung-2j/Medinfora/assets/145014345/305ac452-5c36-4c34-8e82-2d981fcc3f1b)

**Comment by kshksh723** [comment]
글 작성하기 버튼 만들 예정인데 이 뷰단이 괜찮으면  글 작성하기 위치 잡고 진행하겠습니다 ^^

**Comment by jjoung-2j** [comment]
[혜정의견]
- 배너관련 사항은 다른 토의 게시에 따라 이후 토의하면 될것같아요. 만약 Q&A 랑 공지사항만 배너 적용하면 나쁘지않다고 생각하는데 색상은 변경이 필요할 것 같아요.
- 홈->공지사항 은 필요성을 잘 못느끼겠어요.(근데 막상 없으면 중간이 비어보일수도있을거라 생각이 듭니다.)
- 첨부파일 icon 이 들어가는 것은 좋은 아이디어 같아요.
- hover안한 기본색은 좀더 연한 색이였으면 좋겠어요.

**Comment by kshksh723** [comment]
> [혜정의견]
> 
> * 배너관련 사항은 다른 토의 게시에 따라 이후 토의하면 될것같아요. 만약 Q&A 랑 공지사항만 배너 적용하면 나쁘지않다고 생각하는데 색상은 변경이 필요할 것 같아요.
> * 홈->공지사항 은 필요성을 잘 못느끼겠어요.(근데 막상 없으면 중간이 비어보일수도있을거라 생각이 듭니다.)
> * 첨부파일 icon 이 들어가는 것은 좋은 아이디어 같아요.
> * hover안한 기본색은 좀더 연한 색이였으면 좋겠어요.

-- hover 안한 좀 더 연한 색에 그림자 추가할까요?

**Comment by jjoung-2j** [comment]
> > [혜정의견]
> > 
> > * 배너관련 사항은 다른 토의 게시에 따라 이후 토의하면 될것같아요. 만약 Q&A 랑 공지사항만 배너 적용하면 나쁘지않다고 생각하는데 색상은 변경이 필요할 것 같아요.
> > * 홈->공지사항 은 필요성을 잘 못느끼겠어요.(근데 막상 없으면 중간이 비어보일수도있을거라 생각이 듭니다.)
> > * 첨부파일 icon 이 들어가는 것은 좋은 아이디어 같아요.
> > * hover안한 기본색은 좀더 연한 색이였으면 좋겠어요.
> 
> -- hover 안한 좀 더 연한 색에 그림자 추가할까요?

아니면 색없이 있다가 hover 들어온 순간만 색변해도 좋을 것 같아요.
![image](https://github.com/jjoung-2j/Medinfora/assets/145014345/bcf02a18-5f07-4479-87ab-a507a8e218bf)

**Comment by kshksh723** [comment]
> > > [혜정의견]
> > > 
> > > * 배너관련 사항은 다른 토의 게시에 따라 이후 토의하면 될것같아요. 만약 Q&A 랑 공지사항만 배너 적용하면 나쁘지않다고 생각하는데 색상은 변경이 필요할 것 같아요.
> > > * 홈->공지사항 은 필요성을 잘 못느끼겠어요.(근데 막상 없으면 중간이 비어보일수도있을거라 생각이 듭니다.)
> > > * 첨부파일 icon 이 들어가는 것은 좋은 아이디어 같아요.
> > > * hover안한 기본색은 좀더 연한 색이였으면 좋겠어요.
> > 
> > 
> > -- hover 안한 좀 더 연한 색에 그림자 추가할까요?
> 
> 아니면 색없이 있다가 hover 들어온 순간만 색변해도 좋을 것 같아요. ![image](https://private-user-images.githubusercontent.com/145014345/344388499-bcf02a18-5f07-4479-87ab-a507a8e218bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjA5NDcsIm5iZiI6MTcxOTY2MDY0NywicGF0aCI6Ii8xNDUwMTQzNDUvMzQ0Mzg4NDk5LWJjZjAyYTE4LTVmMDctNDQ3OS04N2FiLWE1MDdhOGUyMThiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQxMTMwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjA5YjdkNTBkMTI0MjYxOTNiNDNmNWYzMjg1NGI0YmRiODZhMTY3Y2Y5MWRlN2YzNTU1ODcyNWI2ZTI4NDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5ra4VFCLBd99F0kRuZFvgDFuMUS-wlxKxAnYq4PBBMs)

>>>>>>>>>>>>>>옹 좋습니다!!

**Comment by nime0110** [comment]
[성심의견]
- 공지사항 글자가 적혀있는 이미지가 깨지는 것 같아요. (화질 저하로 인한 자글자글함이 있음) 확인해보시면 좋을 거 같습니다
- 첨부 아이콘 좋은 것 같습니다.
- 홈>공지사항 은 딱히 중간 경로가 없어서 불필요할 수 있을 거 같고, 대신 그 자리에 정렬이나 검색창 들어가도 괜찮을 것 같습니다

**Comment by kshksh723** [comment]
> [성심의견]
> 
> * 공지사항 글자가 적혀있는 이미지가 깨지는 것 같아요. (화질 저하로 인한 자글자글함이 있음) 확인해보시면 좋을 거 같습니다
> * 첨부 아이콘 좋은 것 같습니다.
> * 홈>공지사항 은 딱히 중간 경로가 없어서 불필요할 수 있을 거 같고, 대신 그 자리에 정렬이나 검색창 들어가도 괜찮을 것 같습니다

>> 가져온 사진이 저렇게 디자인된 건데  다른 사진을 넣어야될 것 같아요! 알겠습니다!

**Comment by Forest-Seo** [comment]
[동혁의견]

- 위 혜정의견처럼 (토스 사이트 참고 : https://www.tosspayments.com/notice) 기본 단색에
hover할때 색변환이 있었으면 좋겠어요
- 배너 이미지는 단적으로면 괜찮은거 같은데 다른 페이지와 균형을 위해서라면 제거하는것이 좋아보여요 (비슷한 패턴에 이미지가 있고 공유가 가능하다면 괜찮을꺼같아요.)
- 접혀있는 아코디언 같아요! 테이블 처럼 했으면 좋겠어요~
- 전체 section의 width를 80%에서 좀 줄였으면(70%) 좋겠습니다..!
- 배너 이미지 포지션이 absoulte 인거 같은데 혹시 css에 top위치 조정 하셨는지 궁금합니다 이미지가 해더쪽을 침범해서요!
아니면 의도하신건지 궁금해요
