### ISSUE TITLE
[Bug]버그리스트

### ISSUE THREAD

**Issue by jjoung-2j** [jjoung-2j/Mediinfora#31]
### 버그리스트 양식
- 기능 : 
- 버그 내용 : 
- 수정완료시 comment

**Comment by jjoung-2j** [comment]
[공지사항 - 글 수정]
- 기존에 있던 파일이 삭제되는 현상 발생
- 기존 파일 삭제 버튼이 존재하지 않음

**Comment by kshksh723** [comment]
공지사항 버그 전부 수정 완료

**Comment by jjoung-2j** [comment]
> 공지사항 버그 전부 수정 완료

- 새로운글 등록시 고정핀이 있는 글 위로 올라갑니다.
- 글 조회페이지에서 로그아웃 시 이전페이지로  가는것이 아니라 페이지는 고정으로 부탁드려요.

**Comment by kshksh723** [comment]
> > 공지사항 버그 전부 수정 완료
> 
> * 새로운글 등록시 고정핀이 있는 글 위로 올라갑니다.
> * 글 조회페이지에서 로그아웃 시 이전페이지로  가는것이 아니라 페이지는 고정으로 부탁드려요.
> 
> [참고사진] ![image](https://private-user-images.githubusercontent.com/145014345/348526184-da723acc-eaad-4a80-960f-f58ea8bd5704.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NDgyNTgsIm5iZiI6MTcyMDk0Nzk1OCwicGF0aCI6Ii8xNDUwMTQzNDUvMzQ4NTI2MTg0LWRhNzIzYWNjLWVhYWQtNGE4MC05NjBmLWY1OGVhOGJkNTcwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwOTA1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTFhNGVjN2JhYzI2NWVlY2U0ZjcxMTllZWFjMTNmZGJmMGE2MjRiNzVjOTU3MmYzNTMzNzljZDEyMmI5NDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q_mWoWieHG4qctDgjC-c43KJJrCBCkHy6C79WboU1O0)

-- 고정핀은 이모지여서 해당 글 수정하겠습니다
