### ISSUE TITLE
[Develop]오픈 API DB 접근방안 모색 - 성심

### ISSUE THREAD

**Issue by jjoung-2j** [jjoung-2j/Mediinfora#7]
토론해야 될 안건이나 질문이 생기시면 남겨주세요.

**Comment by nime0110** [comment]
현재 API 에서 XML-> JSON 파싱된 데이터를 saveJsonToFile 함수를 통해 .json 파일로 다운받는 코드 작성 완료 했습니다.
DB에 넣을 예정이라 사용할 특정 칼럼들만 병/의원별로 필터링하여 .json 파일로 다운받는 부분 진행중입니다.  
국립중앙의료원_전국 병·의원 찾기 서비스 API 진행,
[필터링]
"QZ": 병원분류 중
A: 종합병원
B: 병원
C: 의원

병원주소 dutyAddr
진료시간 dutyEtc
기관정보설명 dutyInf => 해당 부분 제외, "척추관절수술 99세까지 88하게.." 등 선전 및 빈 데이터 과다 
기관이름 dutyName
기관연락처 dutyTel1
진료과목 dutyEmclsName
[오픈시간] 월 ~ 일요일(1~7), 공휴일(8)
dutyTime1s
dutyTime2s
dutyTime3s
dutyTime4s
dutyTime5s
dutyTime6s
dutyTime7s
dutyTime8s

[마감시간]월 ~ 일요일(1~7), 공휴일(8) 
dutyTime1c
dutyTime2c
dutyTime3c
dutyTime4c
dutyTime5c
dutyTime6c
dutyTime7c
dutyTime8c

wgs84Lat 위도
wgs84Lon 경도

**Comment by nime0110** [comment]
테이블 생성/ 테이블 칼럼명을 맞춰서 생성했습니다 

ex)
[파라미터]
"QD": "D022",
"QZ": "B",
"numOfRows": "545",
"pageNo":"1"

[json] = DB 테이블 칼럼명과 동일
hpname: element.dutyName?.["#text"] || '', // 병원이름
hpaddr: element.dutyAddr?.["#text"] || '', // 병원주소
hptel: element.dutyTel1?.["#text"] || '', // 병원연락처 
classcode: "D022", //진료과목코드
agency: "종합병원", 
wgs84Lon: element.wgs84Lon?.["#text"] || '', // 경도
wgs84Lat: element.wgs84Lat?.["#text"] || '', // 위도

// --- [오픈시간] ---
starttime1: element.dutyTime1s?.["#text"] || '', // 월요일
starttime2: element.dutyTime2s?.["#text"] || '', // 화요일
starttime3: element.dutyTime3s?.["#text"] || '', // 수요일
starttime4: element.dutyTime4s?.["#text"] || '', // 목요일
starttime5: element.dutyTime5s?.["#text"] || '', // 금요일
starttime6: element.dutyTime6s?.["#text"] || '', // 토요일
starttime7: element.dutyTime7s?.["#text"] || '', // 일요일
starttime8: element.dutyTime8s?.["#text"] || '', // 공휴일

// --- [마감시간] ---
endtime1: element.dutyTime1c?.["#text"] || '', // 월요일
endtime2: element.dutyTime2c?.["#text"] || '', // 화요일
endtime3: element.dutyTime3c?.["#text"] || '', // 수요일
endtime4: element.dutyTime4c?.["#text"] || '', // 목요일
endtime5: element.dutyTime5c?.["#text"] || '', // 금요일
endtime6: element.dutyTime6c?.["#text"] || '', // 토요일
endtime7: element.dutyTime7c?.["#text"] || '', // 일요일
endtime8: element.dutyTime8c?.["#text"] || ''  // 공휴일

**Comment by nime0110** [comment]
[진료과목분류]
내과 D001
소아청소년과 D002
정신건강의학과 D004
피부과 D005
외과 D006
정형외과 D008
산부인과 D011
안과 D012
이비인후과 D013
가정의학과 D022
치과 D026
