### ISSUE TITLE
Medinfora_ERD_ver.1.0(24.06.24)

### ISSUE THREAD

**Issue by jjoung-2j** [jjoung-2j/Mediinfora#9]
# 논리주소
![Medinfora_ERD_ver 1 0(논리)](https://github.com/jjoung-2j/Medinfora/assets/145014345/c816cb28-26ab-419d-80af-03f3226929f5)

# 물리주소
![Medinfora_ERD_ver 1 0(물리)](https://github.com/jjoung-2j/Medinfora/assets/145014345/457706e8-7739-4155-9f90-e5d87cd13306)

**Comment by jjoung-2j** [comment]
@Forest-Seo 로그기록 테이블 추가한거 설명 부탁드려요~

**Comment by Forest-Seo** [comment]
# Redefine ERD (ver1.0.1)

## Logic
![스크린샷 2024-06-26 143311](https://github.com/jjoung-2j/Medinfora/assets/162319225/807c0d57-78bd-4f14-996f-b76fd1ecb369)

## Physical
![스크린샷 2024-06-26 143315](https://github.com/jjoung-2j/Medinfora/assets/162319225/0629f69b-6d0b-4502-9bc7-5562d203ea69)
